/*
 * voxtral_tts_metal.m - Metal GPU implementation for Voxtral TTS
 *
 * Provides GPU-accelerated inference on Apple Silicon using:
 * - Metal Performance Shaders (MPS) for matrix multiplication
 * - Custom Metal compute kernels for attention, normalization, activation
 * - Shared (zero-copy) GPU-CPU buffers for KV cache
 * - Single command buffer encoding for all 26 decoder layers
 *
 * Adapted from antirez/voxtral.c Metal backend.
 */

#ifdef USE_METAL

#import <Foundation/Foundation.h>
#import <Metal/Metal.h>
#import <MetalPerformanceShaders/MetalPerformanceShaders.h>
#include <pthread.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#include "voxtral_tts_metal.h"
#include "voxtral_tts.h"

/* Embedded shader source (generated by: xxd -i voxtral_tts_shaders.metal) */
#include "voxtral_tts_shaders_source.h"

extern int tts_verbose;

/* ========================================================================
 * Global Metal State
 * ======================================================================== */

static id<MTLDevice> g_device = nil;
static id<MTLCommandQueue> g_queue = nil;
static id<MTLLibrary> g_shader_library = nil;
static int g_initialized = 0;

/* Compute pipeline states (one per kernel) */
static id<MTLComputePipelineState> g_rms_norm_pipeline = nil;
static id<MTLComputePipelineState> g_silu_pipeline = nil;
static id<MTLComputePipelineState> g_silu_mul_pipeline = nil;
static id<MTLComputePipelineState> g_add_inplace_pipeline = nil;
static id<MTLComputePipelineState> g_rope_apply_pipeline = nil;
static id<MTLComputePipelineState> g_rope_apply_pos_pipeline = nil;
static id<MTLComputePipelineState> g_kv_cache_copy_pipeline = nil;
static id<MTLComputePipelineState> g_batched_kv_cache_copy_pipeline = nil;
static id<MTLComputePipelineState> g_decoder_attention_pipeline = nil;
static id<MTLComputePipelineState> g_causal_softmax_pipeline = nil;
static id<MTLComputePipelineState> g_bf16_to_f32_pipeline = nil;
static id<MTLComputePipelineState> g_time_embedding_pipeline = nil;
static id<MTLComputePipelineState> g_argmax_pipeline = nil;

/* Persistent GPU buffer for decoder hidden state (cross-layer) */
static id<MTLBuffer> g_dec_x = nil;

/* ========================================================================
 * BF16 -> F16 Weight Cache
 *
 * MPS supports mixed f32/f16 matmul but not f32/bf16. We cache the
 * bf16->f16 conversion per weight pointer (CPU mmap address as key).
 * ======================================================================== */

#define F16_WEIGHT_CACHE_SIZE 512

typedef struct {
    const void *cpu_ptr;
    id<MTLBuffer> gpu_buffer;
    size_t num_elements;
} f16_cache_entry_t;

static f16_cache_entry_t g_f16_cache[F16_WEIGHT_CACHE_SIZE];
static int g_f16_cache_count = 0;
static pthread_mutex_t g_f16_cache_mutex = PTHREAD_MUTEX_INITIALIZER;

static inline uint16_t bf16_to_f16(uint16_t bf16) {
    uint32_t sign = (bf16 >> 15) & 0x1;
    int32_t exp = (bf16 >> 7) & 0xFF;
    uint32_t mant = bf16 & 0x7F;

    if (exp == 0) return (uint16_t)(sign << 15);
    if (exp == 0xFF) return (uint16_t)((sign << 15) | 0x7C00 | (mant ? 0x200 : 0));

    int32_t new_exp = exp - 127 + 15;
    if (new_exp <= 0) return (uint16_t)(sign << 15);
    if (new_exp >= 31) return (uint16_t)((sign << 15) | 0x7C00);

    uint32_t new_mant = mant << 3;
    return (uint16_t)((sign << 15) | (new_exp << 10) | new_mant);
}

static id<MTLBuffer> get_cached_f16_buffer(const uint16_t *weights, size_t num_elements) {
    pthread_mutex_lock(&g_f16_cache_mutex);

    for (int i = 0; i < g_f16_cache_count; i++) {
        if (g_f16_cache[i].cpu_ptr == (const void *)weights) {
            id<MTLBuffer> buf = g_f16_cache[i].gpu_buffer;
            pthread_mutex_unlock(&g_f16_cache_mutex);
            return buf;
        }
    }

    uint16_t *f16_data = (uint16_t *)malloc(num_elements * sizeof(uint16_t));
    for (size_t i = 0; i < num_elements; i++)
        f16_data[i] = bf16_to_f16(weights[i]);

    id<MTLBuffer> buf = [g_device newBufferWithBytes:f16_data
                                              length:num_elements * sizeof(uint16_t)
                                             options:MTLResourceStorageModeShared];
    free(f16_data);

    if (g_f16_cache_count < F16_WEIGHT_CACHE_SIZE) {
        g_f16_cache[g_f16_cache_count].cpu_ptr = (const void *)weights;
        g_f16_cache[g_f16_cache_count].gpu_buffer = buf;
        g_f16_cache[g_f16_cache_count].num_elements = num_elements;
        g_f16_cache_count++;
    }

    pthread_mutex_unlock(&g_f16_cache_mutex);
    return buf;
}

/* ========================================================================
 * F32 Weight/Activation Buffer Cache
 * ======================================================================== */

#define WEIGHT_CACHE_SIZE 256

typedef struct {
    const void *cpu_ptr;
    id<MTLBuffer> gpu_buffer;
    size_t size;
} weight_cache_entry_t;

static weight_cache_entry_t g_weight_cache[WEIGHT_CACHE_SIZE];
static int g_weight_cache_count = 0;

static id<MTLBuffer> get_f32_buffer(const float *data, size_t n_floats) {
    /* Check cache */
    for (int i = 0; i < g_weight_cache_count; i++) {
        if (g_weight_cache[i].cpu_ptr == data)
            return g_weight_cache[i].gpu_buffer;
    }

    /* Upload */
    size_t bytes = n_floats * sizeof(float);
    id<MTLBuffer> buf = [g_device newBufferWithBytes:data
                                              length:bytes
                                             options:MTLResourceStorageModeManaged];

    if (g_weight_cache_count < WEIGHT_CACHE_SIZE) {
        g_weight_cache[g_weight_cache_count].cpu_ptr = data;
        g_weight_cache[g_weight_cache_count].gpu_buffer = buf;
        g_weight_cache[g_weight_cache_count].size = bytes;
        g_weight_cache_count++;
    }

    return buf;
}

/* ========================================================================
 * Shared Memory Allocation (Zero-Copy GPU-CPU)
 * ======================================================================== */

#define SHARED_ALLOC_MAX 16

static struct {
    void *ptr;
    id<MTLBuffer> buf;
} g_shared_allocs[SHARED_ALLOC_MAX];
static int g_shared_count = 0;

void *tts_metal_shared_alloc(size_t size) {
    if (!g_initialized || g_shared_count >= SHARED_ALLOC_MAX)
        return calloc(1, size);

    id<MTLBuffer> buf = [g_device newBufferWithLength:size
                                              options:MTLResourceStorageModeShared];
    if (!buf) return calloc(1, size);

    void *ptr = [buf contents];
    memset(ptr, 0, size);

    g_shared_allocs[g_shared_count].ptr = ptr;
    g_shared_allocs[g_shared_count].buf = buf;
    g_shared_count++;

    return ptr;
}

void tts_metal_shared_free(void *ptr) {
    for (int i = 0; i < g_shared_count; i++) {
        if (g_shared_allocs[i].ptr == ptr) {
            g_shared_allocs[i].buf = nil;
            /* Shift remaining entries */
            for (int j = i; j < g_shared_count - 1; j++)
                g_shared_allocs[j] = g_shared_allocs[j + 1];
            g_shared_count--;
            return;
        }
    }
    free(ptr); /* Not a shared alloc, must be calloc fallback */
}

static id<MTLBuffer> find_shared_buffer(const void *ptr) {
    for (int i = 0; i < g_shared_count; i++) {
        if (g_shared_allocs[i].ptr == ptr)
            return g_shared_allocs[i].buf;
    }
    return nil;
}

/* ========================================================================
 * Activation Buffer Pool (reusable scratch buffers)
 * ======================================================================== */

#define ACTIVATION_POOL_SIZE 32

static struct {
    id<MTLBuffer> buf;
    size_t size;
    int in_use;
} g_activation_pool[ACTIVATION_POOL_SIZE];
static int g_pool_count = 0;

static id<MTLBuffer> pool_get_buffer(size_t size) {
    /* Try to find a reusable buffer of sufficient size */
    for (int i = 0; i < g_pool_count; i++) {
        if (!g_activation_pool[i].in_use && g_activation_pool[i].size >= size) {
            g_activation_pool[i].in_use = 1;
            return g_activation_pool[i].buf;
        }
    }

    /* Allocate new */
    id<MTLBuffer> buf = [g_device newBufferWithLength:size
                                              options:MTLResourceStorageModeShared];
    if (g_pool_count < ACTIVATION_POOL_SIZE) {
        g_activation_pool[g_pool_count].buf = buf;
        g_activation_pool[g_pool_count].size = size;
        g_activation_pool[g_pool_count].in_use = 1;
        g_pool_count++;
    }
    return buf;
}

static void pool_release_buffer(id<MTLBuffer> buf) {
    for (int i = 0; i < g_pool_count; i++) {
        if (g_activation_pool[i].buf == buf) {
            g_activation_pool[i].in_use = 0;
            return;
        }
    }
}

/* ========================================================================
 * Shader Initialization
 * ======================================================================== */

static int init_shaders(void) {
    NSString *shaderSource = [[NSString alloc]
        initWithBytes:voxtral_tts_shaders_metal
               length:voxtral_tts_shaders_metal_len
             encoding:NSUTF8StringEncoding];

    MTLCompileOptions *options = [[MTLCompileOptions alloc] init];
    options.mathMode = MTLMathModeFast;

    NSError *error = nil;
    g_shader_library = [g_device newLibraryWithSource:shaderSource
                                              options:options
                                                error:&error];
    if (!g_shader_library) {
        fprintf(stderr, "metal: shader compilation failed: %s\n",
                [[error description] UTF8String]);
        return -1;
    }

    /* Create pipeline states for each kernel */
    struct { const char *name; id<MTLComputePipelineState> __strong *pipeline; } kernels[] = {
        {"rms_norm", &g_rms_norm_pipeline},
        {"silu", &g_silu_pipeline},
        {"silu_mul", &g_silu_mul_pipeline},
        {"add_inplace", &g_add_inplace_pipeline},
        {"rope_apply", &g_rope_apply_pipeline},
        {"rope_apply_pos", &g_rope_apply_pos_pipeline},
        {"kv_cache_copy", &g_kv_cache_copy_pipeline},
        {"batched_kv_cache_copy", &g_batched_kv_cache_copy_pipeline},
        {"decoder_attention", &g_decoder_attention_pipeline},
        {"causal_softmax", &g_causal_softmax_pipeline},
        {"bf16_to_f32", &g_bf16_to_f32_pipeline},
        {"time_embedding", &g_time_embedding_pipeline},
        {"argmax", &g_argmax_pipeline},
        {NULL, NULL}
    };

    for (int i = 0; kernels[i].name; i++) {
        NSString *name = [NSString stringWithUTF8String:kernels[i].name];
        id<MTLFunction> func = [g_shader_library newFunctionWithName:name];
        if (func) {
            *kernels[i].pipeline = [g_device newComputePipelineStateWithFunction:func
                                                                           error:&error];
            if (!*kernels[i].pipeline) {
                fprintf(stderr, "metal: pipeline creation failed for %s: %s\n",
                        kernels[i].name, [[error description] UTF8String]);
            }
        } else {
            fprintf(stderr, "metal: kernel '%s' not found in shader library\n",
                    kernels[i].name);
        }
    }

    return 0;
}

/* ========================================================================
 * Metal Initialization
 * ======================================================================== */

int tts_metal_init(void) {
    @autoreleasepool {
        g_device = MTLCreateSystemDefaultDevice();
        if (!g_device) {
            fprintf(stderr, "metal: no Metal device found\n");
            return 0;
        }

        /* Check GPU family (require Apple6+ for good performance) */
        if (![g_device supportsFamily:MTLGPUFamilyApple7] &&
            ![g_device supportsFamily:MTLGPUFamilyApple6]) {
            fprintf(stderr, "metal: GPU family too old (need Apple6+)\n");
            return 0;
        }

        g_queue = [g_device newCommandQueue];
        if (!g_queue) {
            fprintf(stderr, "metal: failed to create command queue\n");
            return 0;
        }

        if (init_shaders() != 0) {
            return 0;
        }

        g_initialized = 1;

        if (tts_verbose)
            fprintf(stderr, "  Metal: %s, %.1f GB\n",
                    [[g_device name] UTF8String],
                    (float)[g_device recommendedMaxWorkingSetSize] / (1024*1024*1024));
    }
    return 1;
}

int tts_metal_available(void) {
    return g_initialized;
}

void tts_metal_shutdown(void) {
    if (!g_initialized) return;

    /* Release caches */
    for (int i = 0; i < g_f16_cache_count; i++)
        g_f16_cache[i].gpu_buffer = nil;
    g_f16_cache_count = 0;

    for (int i = 0; i < g_weight_cache_count; i++)
        g_weight_cache[i].gpu_buffer = nil;
    g_weight_cache_count = 0;

    for (int i = 0; i < g_pool_count; i++)
        g_activation_pool[i].buf = nil;
    g_pool_count = 0;

    for (int i = 0; i < g_shared_count; i++)
        g_shared_allocs[i].buf = nil;
    g_shared_count = 0;

    g_dec_x = nil;

    /* Release pipelines */
    g_rms_norm_pipeline = nil;
    g_silu_pipeline = nil;
    g_silu_mul_pipeline = nil;
    g_add_inplace_pipeline = nil;
    g_rope_apply_pipeline = nil;
    g_rope_apply_pos_pipeline = nil;
    g_kv_cache_copy_pipeline = nil;
    g_batched_kv_cache_copy_pipeline = nil;
    g_decoder_attention_pipeline = nil;
    g_causal_softmax_pipeline = nil;
    g_bf16_to_f32_pipeline = nil;
    g_time_embedding_pipeline = nil;
    g_argmax_pipeline = nil;

    g_shader_library = nil;
    g_queue = nil;
    g_device = nil;
    g_initialized = 0;
}

/* ========================================================================
 * MPS Matrix Multiplication
 * ======================================================================== */

void tts_metal_sgemm_bf16(int M, int N, int K,
                           const float *A, const uint16_t *B_bf16, float *C) {
    @autoreleasepool {
        /* Convert bf16 -> f16 for weights (half memory, good enough for most layers).
         * Apple Silicon unified memory means shared buffers are zero-copy. */
        id<MTLBuffer> bufB = get_cached_f16_buffer(B_bf16, (size_t)N * K);

        id<MTLBuffer> bufA = [g_device newBufferWithBytes:A
                                                   length:(size_t)M * K * sizeof(float)
                                                  options:MTLResourceStorageModeShared];
        id<MTLBuffer> bufC = [g_device newBufferWithLength:(size_t)M * N * sizeof(float)
                                                   options:MTLResourceStorageModeShared];

        /* Mixed precision: f32 activations x f16 weights -> f32 output */
        MPSMatrixDescriptor *descA = [MPSMatrixDescriptor
            matrixDescriptorWithRows:M columns:K rowBytes:K * sizeof(float)
            dataType:MPSDataTypeFloat32];
        MPSMatrixDescriptor *descB = [MPSMatrixDescriptor
            matrixDescriptorWithRows:N columns:K rowBytes:K * sizeof(uint16_t)
            dataType:MPSDataTypeFloat16];
        MPSMatrixDescriptor *descC = [MPSMatrixDescriptor
            matrixDescriptorWithRows:M columns:N rowBytes:N * sizeof(float)
            dataType:MPSDataTypeFloat32];

        MPSMatrix *matA = [[MPSMatrix alloc] initWithBuffer:bufA descriptor:descA];
        MPSMatrix *matB = [[MPSMatrix alloc] initWithBuffer:bufB descriptor:descB];
        MPSMatrix *matC = [[MPSMatrix alloc] initWithBuffer:bufC descriptor:descC];

        MPSMatrixMultiplication *mm = [[MPSMatrixMultiplication alloc]
            initWithDevice:g_device
             transposeLeft:NO
            transposeRight:YES
                resultRows:M
             resultColumns:N
           interiorColumns:K
                     alpha:1.0
                      beta:0.0];

        id<MTLCommandBuffer> cmdBuffer = [g_queue commandBuffer];
        [mm encodeToCommandBuffer:cmdBuffer leftMatrix:matA rightMatrix:matB
                     resultMatrix:matC];
        [cmdBuffer commit];
        [cmdBuffer waitUntilCompleted];

        memcpy(C, [bufC contents], (size_t)M * N * sizeof(float));
    }
}

void tts_metal_sgemm(int M, int N, int K,
                     const float *A, const float *B, float *C) {
    @autoreleasepool {
        id<MTLBuffer> bufA = [g_device newBufferWithBytes:A
                                                   length:(size_t)M * K * sizeof(float)
                                                  options:MTLResourceStorageModeShared];
        id<MTLBuffer> bufB = [g_device newBufferWithBytes:B
                                                   length:(size_t)N * K * sizeof(float)
                                                  options:MTLResourceStorageModeShared];
        id<MTLBuffer> bufC = [g_device newBufferWithLength:(size_t)M * N * sizeof(float)
                                                   options:MTLResourceStorageModeShared];

        MPSMatrixDescriptor *descA = [MPSMatrixDescriptor
            matrixDescriptorWithRows:M columns:K rowBytes:K * sizeof(float)
            dataType:MPSDataTypeFloat32];
        MPSMatrixDescriptor *descB = [MPSMatrixDescriptor
            matrixDescriptorWithRows:N columns:K rowBytes:K * sizeof(float)
            dataType:MPSDataTypeFloat32];
        MPSMatrixDescriptor *descC = [MPSMatrixDescriptor
            matrixDescriptorWithRows:M columns:N rowBytes:N * sizeof(float)
            dataType:MPSDataTypeFloat32];

        MPSMatrix *matA = [[MPSMatrix alloc] initWithBuffer:bufA descriptor:descA];
        MPSMatrix *matB = [[MPSMatrix alloc] initWithBuffer:bufB descriptor:descB];
        MPSMatrix *matC = [[MPSMatrix alloc] initWithBuffer:bufC descriptor:descC];

        MPSMatrixMultiplication *mm = [[MPSMatrixMultiplication alloc]
            initWithDevice:g_device transposeLeft:NO transposeRight:YES
                resultRows:M resultColumns:N interiorColumns:K alpha:1.0 beta:0.0];

        id<MTLCommandBuffer> cmdBuffer = [g_queue commandBuffer];
        [mm encodeToCommandBuffer:cmdBuffer leftMatrix:matA rightMatrix:matB
                     resultMatrix:matC];
        [cmdBuffer commit];
        [cmdBuffer waitUntilCompleted];

        memcpy(C, [bufC contents], (size_t)M * N * sizeof(float));
    }
}

/* ========================================================================
 * Standalone Kernel Wrappers (for test harness + individual dispatch)
 * ======================================================================== */

void tts_metal_rms_norm(float *out, const float *x, const float *weight,
                        int seq_len, int hidden, float eps) {
    @autoreleasepool {
        id<MTLBuffer> bufX = [g_device newBufferWithBytes:x length:seq_len * hidden * sizeof(float)
                                                  options:MTLResourceStorageModeShared];
        id<MTLBuffer> bufW = [g_device newBufferWithBytes:weight length:hidden * sizeof(float)
                                                  options:MTLResourceStorageModeShared];
        id<MTLBuffer> bufOut = [g_device newBufferWithLength:seq_len * hidden * sizeof(float)
                                                     options:MTLResourceStorageModeShared];

        id<MTLCommandBuffer> cmd = [g_queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cmd computeCommandEncoder];
        [enc setComputePipelineState:g_rms_norm_pipeline];
        [enc setBuffer:bufX offset:0 atIndex:0];
        [enc setBuffer:bufW offset:0 atIndex:1];
        [enc setBuffer:bufOut offset:0 atIndex:2];
        [enc setBytes:&hidden length:sizeof(int) atIndex:3];
        [enc setBytes:&eps length:sizeof(float) atIndex:4];
        [enc dispatchThreadgroups:MTLSizeMake(seq_len, 1, 1)
            threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
        [enc endEncoding];
        [cmd commit];
        [cmd waitUntilCompleted];

        memcpy(out, [bufOut contents], seq_len * hidden * sizeof(float));
    }
}

void tts_metal_silu_mul(float *gate, const float *up, int n) {
    @autoreleasepool {
        id<MTLBuffer> bufGate = [g_device newBufferWithBytes:gate length:n * sizeof(float)
                                                     options:MTLResourceStorageModeShared];
        id<MTLBuffer> bufUp = [g_device newBufferWithBytes:up length:n * sizeof(float)
                                                   options:MTLResourceStorageModeShared];

        id<MTLCommandBuffer> cmd = [g_queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cmd computeCommandEncoder];
        [enc setComputePipelineState:g_silu_mul_pipeline];
        [enc setBuffer:bufGate offset:0 atIndex:0];
        [enc setBuffer:bufUp offset:0 atIndex:1];
        [enc setBytes:&n length:sizeof(int) atIndex:2];
        [enc dispatchThreads:MTLSizeMake(n, 1, 1)
            threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
        [enc endEncoding];
        [cmd commit];
        [cmd waitUntilCompleted];

        memcpy(gate, [bufGate contents], n * sizeof(float));
    }
}

void tts_metal_add_inplace(float *a, const float *b, int n) {
    @autoreleasepool {
        id<MTLBuffer> bufA = [g_device newBufferWithBytes:a length:n * sizeof(float)
                                                  options:MTLResourceStorageModeShared];
        id<MTLBuffer> bufB = [g_device newBufferWithBytes:b length:n * sizeof(float)
                                                  options:MTLResourceStorageModeShared];

        id<MTLCommandBuffer> cmd = [g_queue commandBuffer];
        id<MTLComputeCommandEncoder> enc = [cmd computeCommandEncoder];
        [enc setComputePipelineState:g_add_inplace_pipeline];
        [enc setBuffer:bufA offset:0 atIndex:0];
        [enc setBuffer:bufB offset:0 atIndex:1];
        [enc setBytes:&n length:sizeof(int) atIndex:2];
        [enc dispatchThreads:MTLSizeMake(n, 1, 1)
            threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
        [enc endEncoding];
        [cmd commit];
        [cmd waitUntilCompleted];

        memcpy(a, [bufA contents], n * sizeof(float));
    }
}

/* ========================================================================
 * Monolithic LLM Decoder Forward (all 26 layers in one command buffer)
 * ======================================================================== */

void tts_metal_llm_forward(void *ctx_ptr, const float *input_embed,
                            float *out_hidden, int pos) {
    @autoreleasepool {
        tts_ctx_t *ctx = (tts_ctx_t *)ctx_ptr;
        tts_decoder_t *dec = &ctx->decoder;
        int dim = TTS_DEC_DIM;
        int q_dim = TTS_DEC_HEADS * TTS_DEC_HEAD_DIM;
        int kv_dim = TTS_DEC_KV_HEADS * TTS_DEC_HEAD_DIM;
        int hidden = TTS_DEC_HIDDEN;
        float scale = 1.0f / sqrtf((float)TTS_DEC_HEAD_DIM);

        /* Get/create persistent x buffer */
        if (!g_dec_x) {
            g_dec_x = [g_device newBufferWithLength:dim * sizeof(float)
                                            options:MTLResourceStorageModeShared];
        }

        /* Upload input embedding */
        memcpy([g_dec_x contents], input_embed, dim * sizeof(float));

        /* Allocate scratch buffers from pool */
        id<MTLBuffer> bufXnorm = pool_get_buffer(dim * sizeof(float));
        id<MTLBuffer> bufQKV = pool_get_buffer((q_dim + kv_dim + kv_dim) * sizeof(float));
        id<MTLBuffer> bufAttn = pool_get_buffer(q_dim * sizeof(float));
        id<MTLBuffer> bufProj = pool_get_buffer(dim * sizeof(float));
        id<MTLBuffer> bufGate = pool_get_buffer(hidden * sizeof(float));
        id<MTLBuffer> bufUp = pool_get_buffer(hidden * sizeof(float));
        id<MTLBuffer> bufFfnOut = pool_get_buffer(dim * sizeof(float));

        /* Find KV cache shared buffers */
        id<MTLBuffer> gpu_kv_k = find_shared_buffer(ctx->kv_cache_k);
        id<MTLBuffer> gpu_kv_v = find_shared_buffer(ctx->kv_cache_v);

        /* Create single command buffer for ALL 26 layers */
        id<MTLCommandBuffer> cmdBuffer = [g_queue commandBuffer];

        for (int layer = 0; layer < TTS_DEC_LAYERS; layer++) {
            tts_dec_layer_t *l = &dec->layers[layer];

            /* === RMSNorm === */
            id<MTLBuffer> bufNormW = get_f32_buffer(l->attention_norm, dim);
            {
                id<MTLComputeCommandEncoder> enc = [cmdBuffer computeCommandEncoder];
                [enc setComputePipelineState:g_rms_norm_pipeline];
                [enc setBuffer:g_dec_x offset:0 atIndex:0];
                [enc setBuffer:bufNormW offset:0 atIndex:1];
                [enc setBuffer:bufXnorm offset:0 atIndex:2];
                [enc setBytes:&dim length:sizeof(int) atIndex:3];
                float eps = TTS_DEC_NORM_EPS;
                [enc setBytes:&eps length:sizeof(float) atIndex:4];
                [enc dispatchThreadgroups:MTLSizeMake(1, 1, 1)
                    threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
                [enc endEncoding];
            }

            /* === Q, K, V projections (MPS matmul) === */
            id<MTLBuffer> bufWq = get_cached_f16_buffer(l->wq_bf16, (size_t)q_dim * dim);
            id<MTLBuffer> bufWk = get_cached_f16_buffer(l->wk_bf16, (size_t)kv_dim * dim);
            id<MTLBuffer> bufWv = get_cached_f16_buffer(l->wv_bf16, (size_t)kv_dim * dim);

            /* Q = x_norm @ Wq^T */
            MPSMatrixDescriptor *descX1 = [MPSMatrixDescriptor
                matrixDescriptorWithRows:1 columns:dim rowBytes:dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matXnorm = [[MPSMatrix alloc] initWithBuffer:bufXnorm descriptor:descX1];

            MPSMatrixDescriptor *descWq = [MPSMatrixDescriptor
                matrixDescriptorWithRows:q_dim columns:dim rowBytes:dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matWq = [[MPSMatrix alloc] initWithBuffer:bufWq descriptor:descWq];

            MPSMatrixDescriptor *descQ = [MPSMatrixDescriptor
                matrixDescriptorWithRows:1 columns:q_dim rowBytes:q_dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matQ = [[MPSMatrix alloc] initWithBuffer:bufQKV descriptor:descQ];

            MPSMatrixMultiplication *mmQ = [[MPSMatrixMultiplication alloc]
                initWithDevice:g_device transposeLeft:NO transposeRight:YES
                    resultRows:1 resultColumns:q_dim interiorColumns:dim alpha:1.0 beta:0.0];
            [mmQ encodeToCommandBuffer:cmdBuffer leftMatrix:matXnorm rightMatrix:matWq resultMatrix:matQ];

            /* K = x_norm @ Wk^T */
            MPSMatrixDescriptor *descWk = [MPSMatrixDescriptor
                matrixDescriptorWithRows:kv_dim columns:dim rowBytes:dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matWk = [[MPSMatrix alloc] initWithBuffer:bufWk descriptor:descWk];

            MPSMatrixDescriptor *descK = [MPSMatrixDescriptor
                matrixDescriptorWithRows:1 columns:kv_dim rowBytes:kv_dim*sizeof(float) dataType:MPSDataTypeFloat32];
            MPSMatrix *matK = [[MPSMatrix alloc] initWithBuffer:bufQKV offset:q_dim*sizeof(float) descriptor:descK];

            MPSMatrixMultiplication *mmK = [[MPSMatrixMultiplication alloc]
                initWithDevice:g_device transposeLeft:NO transposeRight:YES
                    resultRows:1 resultColumns:kv_dim interiorColumns:dim alpha:1.0 beta:0.0];
            [mmK encodeToCommandBuffer:cmdBuffer leftMatrix:matXnorm rightMatrix:matWk resultMatrix:matK];

            /* V = x_norm @ Wv^T */
            MPSMatrixDescriptor *descWv = [MPSMatrixDescriptor
                matrixDescriptorWithRows:kv_dim columns:dim rowBytes:dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matWv = [[MPSMatrix alloc] initWithBuffer:bufWv descriptor:descWv];

            MPSMatrixDescriptor *descV = [MPSMatrixDescriptor
                matrixDescriptorWithRows:1 columns:kv_dim rowBytes:kv_dim*sizeof(float) dataType:MPSDataTypeFloat32];
            MPSMatrix *matV = [[MPSMatrix alloc] initWithBuffer:bufQKV offset:(q_dim+kv_dim)*sizeof(float) descriptor:descV];

            MPSMatrixMultiplication *mmV = [[MPSMatrixMultiplication alloc]
                initWithDevice:g_device transposeLeft:NO transposeRight:YES
                    resultRows:1 resultColumns:kv_dim interiorColumns:dim alpha:1.0 beta:0.0];
            [mmV encodeToCommandBuffer:cmdBuffer leftMatrix:matXnorm rightMatrix:matWv resultMatrix:matV];

            /* === RoPE + KV cache + Attention === */
            {
                id<MTLComputeCommandEncoder> enc = [cmdBuffer computeCommandEncoder];

                /* RoPE on Q */
                [enc setComputePipelineState:g_rope_apply_pos_pipeline];
                [enc setBuffer:bufQKV offset:0 atIndex:0];
                int n_heads = TTS_DEC_HEADS;
                int head_dim = TTS_DEC_HEAD_DIM;
                float rope_theta = TTS_ROPE_THETA;
                [enc setBytes:&n_heads length:sizeof(int) atIndex:1];
                [enc setBytes:&head_dim length:sizeof(int) atIndex:2];
                [enc setBytes:&pos length:sizeof(int) atIndex:3];
                [enc setBytes:&rope_theta length:sizeof(float) atIndex:4];
                int tg = MIN(n_heads * head_dim / 2, 256);
                [enc dispatchThreads:MTLSizeMake(n_heads * head_dim / 2, 1, 1)
                    threadsPerThreadgroup:MTLSizeMake(tg, 1, 1)];

                /* RoPE on K */
                [enc setBuffer:bufQKV offset:q_dim * sizeof(float) atIndex:0];
                int n_kv = TTS_DEC_KV_HEADS;
                [enc setBytes:&n_kv length:sizeof(int) atIndex:1];
                [enc dispatchThreads:MTLSizeMake(n_kv * head_dim / 2, 1, 1)
                    threadsPerThreadgroup:MTLSizeMake(MIN(n_kv * head_dim / 2, 256), 1, 1)];

                [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];

                /* Write K to cache */
                if (gpu_kv_k) {
                    [enc setComputePipelineState:g_kv_cache_copy_pipeline];
                    [enc setBuffer:gpu_kv_k offset:0 atIndex:0];
                    [enc setBuffer:bufQKV offset:q_dim * sizeof(float) atIndex:1];
                    int kv_offset = ((int)((size_t)layer * ctx->kv_cache_max + pos) * kv_dim);
                    [enc setBytes:&kv_offset length:sizeof(int) atIndex:2];
                    [enc setBytes:&kv_dim length:sizeof(int) atIndex:3];
                    [enc dispatchThreads:MTLSizeMake(kv_dim, 1, 1)
                        threadsPerThreadgroup:MTLSizeMake(MIN(kv_dim, 256), 1, 1)];

                    /* Write V to cache */
                    [enc setBuffer:gpu_kv_v offset:0 atIndex:0];
                    [enc setBuffer:bufQKV offset:(q_dim + kv_dim) * sizeof(float) atIndex:1];
                    [enc dispatchThreads:MTLSizeMake(kv_dim, 1, 1)
                        threadsPerThreadgroup:MTLSizeMake(MIN(kv_dim, 256), 1, 1)];

                    [enc memoryBarrierWithScope:MTLBarrierScopeBuffers];

                    /* Attention */
                    [enc setComputePipelineState:g_decoder_attention_pipeline];
                    [enc setBuffer:bufQKV offset:0 atIndex:0]; /* Q */
                    size_t layer_kv_offset = (size_t)layer * ctx->kv_cache_max * kv_dim * sizeof(float);
                    [enc setBuffer:gpu_kv_k offset:layer_kv_offset atIndex:1];
                    [enc setBuffer:gpu_kv_v offset:layer_kv_offset atIndex:2];
                    [enc setBuffer:bufAttn offset:0 atIndex:3];
                    [enc setBytes:&n_heads length:sizeof(int) atIndex:4];
                    int n_kv_heads = TTS_DEC_KV_HEADS;
                    [enc setBytes:&n_kv_heads length:sizeof(int) atIndex:5];
                    [enc setBytes:&head_dim length:sizeof(int) atIndex:6];
                    [enc setBytes:&kv_dim length:sizeof(int) atIndex:7];
                    int seq_k = pos + 1;
                    [enc setBytes:&seq_k length:sizeof(int) atIndex:8];
                    [enc setBytes:&scale length:sizeof(float) atIndex:9];
                    int win = 0;
                    [enc setBytes:&win length:sizeof(int) atIndex:10];
                    [enc setBytes:&pos length:sizeof(int) atIndex:11];
                    [enc dispatchThreadgroups:MTLSizeMake(n_heads, 1, 1)
                        threadsPerThreadgroup:MTLSizeMake(128, 1, 1)];
                }

                [enc endEncoding];
            }

            /* === WO projection === */
            id<MTLBuffer> bufWo = get_cached_f16_buffer(l->wo_bf16, (size_t)dim * q_dim);
            MPSMatrixDescriptor *descAttn = [MPSMatrixDescriptor
                matrixDescriptorWithRows:1 columns:q_dim rowBytes:q_dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matAttn = [[MPSMatrix alloc] initWithBuffer:bufAttn descriptor:descAttn];

            MPSMatrixDescriptor *descWo = [MPSMatrixDescriptor
                matrixDescriptorWithRows:dim columns:q_dim rowBytes:q_dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matWo = [[MPSMatrix alloc] initWithBuffer:bufWo descriptor:descWo];

            MPSMatrixDescriptor *descProj = [MPSMatrixDescriptor
                matrixDescriptorWithRows:1 columns:dim rowBytes:dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matProj = [[MPSMatrix alloc] initWithBuffer:bufProj descriptor:descProj];

            MPSMatrixMultiplication *mmWo = [[MPSMatrixMultiplication alloc]
                initWithDevice:g_device transposeLeft:NO transposeRight:YES
                    resultRows:1 resultColumns:dim interiorColumns:q_dim alpha:1.0 beta:0.0];
            [mmWo encodeToCommandBuffer:cmdBuffer leftMatrix:matAttn rightMatrix:matWo resultMatrix:matProj];

            /* === Residual: x += proj === */
            {
                id<MTLComputeCommandEncoder> enc = [cmdBuffer computeCommandEncoder];
                [enc setComputePipelineState:g_add_inplace_pipeline];
                [enc setBuffer:g_dec_x offset:0 atIndex:0];
                [enc setBuffer:bufProj offset:0 atIndex:1];
                [enc setBytes:&dim length:sizeof(int) atIndex:2];
                [enc dispatchThreads:MTLSizeMake(dim, 1, 1)
                    threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
                [enc endEncoding];
            }

            /* === FFN: RMSNorm + SwiGLU === */
            id<MTLBuffer> bufFfnNormW = get_f32_buffer(l->ffn_norm, dim);
            {
                id<MTLComputeCommandEncoder> enc = [cmdBuffer computeCommandEncoder];
                [enc setComputePipelineState:g_rms_norm_pipeline];
                [enc setBuffer:g_dec_x offset:0 atIndex:0];
                [enc setBuffer:bufFfnNormW offset:0 atIndex:1];
                [enc setBuffer:bufXnorm offset:0 atIndex:2];
                [enc setBytes:&dim length:sizeof(int) atIndex:3];
                float eps = TTS_DEC_NORM_EPS;
                [enc setBytes:&eps length:sizeof(float) atIndex:4];
                [enc dispatchThreadgroups:MTLSizeMake(1, 1, 1)
                    threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
                [enc endEncoding];
            }

            /* w1 (gate) */
            id<MTLBuffer> bufW1 = get_cached_f16_buffer(l->w1_bf16, (size_t)hidden * dim);
            MPSMatrixDescriptor *descW1 = [MPSMatrixDescriptor
                matrixDescriptorWithRows:hidden columns:dim rowBytes:dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matW1 = [[MPSMatrix alloc] initWithBuffer:bufW1 descriptor:descW1];
            MPSMatrixDescriptor *descGate = [MPSMatrixDescriptor
                matrixDescriptorWithRows:1 columns:hidden rowBytes:hidden*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matGate = [[MPSMatrix alloc] initWithBuffer:bufGate descriptor:descGate];
            MPSMatrixMultiplication *mmW1 = [[MPSMatrixMultiplication alloc]
                initWithDevice:g_device transposeLeft:NO transposeRight:YES
                    resultRows:1 resultColumns:hidden interiorColumns:dim alpha:1.0 beta:0.0];
            [mmW1 encodeToCommandBuffer:cmdBuffer leftMatrix:matXnorm rightMatrix:matW1 resultMatrix:matGate];

            /* w3 (up) */
            id<MTLBuffer> bufW3 = get_cached_f16_buffer(l->w3_bf16, (size_t)hidden * dim);
            MPSMatrixDescriptor *descW3 = [MPSMatrixDescriptor
                matrixDescriptorWithRows:hidden columns:dim rowBytes:dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matW3 = [[MPSMatrix alloc] initWithBuffer:bufW3 descriptor:descW3];
            MPSMatrixDescriptor *descUp = [MPSMatrixDescriptor
                matrixDescriptorWithRows:1 columns:hidden rowBytes:hidden*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matUp = [[MPSMatrix alloc] initWithBuffer:bufUp descriptor:descUp];
            MPSMatrixMultiplication *mmW3 = [[MPSMatrixMultiplication alloc]
                initWithDevice:g_device transposeLeft:NO transposeRight:YES
                    resultRows:1 resultColumns:hidden interiorColumns:dim alpha:1.0 beta:0.0];
            [mmW3 encodeToCommandBuffer:cmdBuffer leftMatrix:matXnorm rightMatrix:matW3 resultMatrix:matUp];

            /* Fused SiLU(gate) * up */
            {
                id<MTLComputeCommandEncoder> enc = [cmdBuffer computeCommandEncoder];
                [enc setComputePipelineState:g_silu_mul_pipeline];
                [enc setBuffer:bufGate offset:0 atIndex:0];
                [enc setBuffer:bufUp offset:0 atIndex:1];
                [enc setBytes:&hidden length:sizeof(int) atIndex:2];
                [enc dispatchThreads:MTLSizeMake(hidden, 1, 1)
                    threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
                [enc endEncoding];
            }

            /* w2 (down) */
            id<MTLBuffer> bufW2 = get_cached_f16_buffer(l->w2_bf16, (size_t)dim * hidden);
            MPSMatrixDescriptor *descW2 = [MPSMatrixDescriptor
                matrixDescriptorWithRows:dim columns:hidden rowBytes:hidden*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matW2 = [[MPSMatrix alloc] initWithBuffer:bufW2 descriptor:descW2];
            MPSMatrixDescriptor *descFfnOut = [MPSMatrixDescriptor
                matrixDescriptorWithRows:1 columns:dim rowBytes:dim*sizeof(uint16_t) dataType:MPSDataTypeFloat16];
            MPSMatrix *matFfnOut = [[MPSMatrix alloc] initWithBuffer:bufFfnOut descriptor:descFfnOut];
            MPSMatrixMultiplication *mmW2 = [[MPSMatrixMultiplication alloc]
                initWithDevice:g_device transposeLeft:NO transposeRight:YES
                    resultRows:1 resultColumns:dim interiorColumns:hidden alpha:1.0 beta:0.0];
            [mmW2 encodeToCommandBuffer:cmdBuffer leftMatrix:matGate rightMatrix:matW2 resultMatrix:matFfnOut];

            /* Residual: x += ffn_out */
            {
                id<MTLComputeCommandEncoder> enc = [cmdBuffer computeCommandEncoder];
                [enc setComputePipelineState:g_add_inplace_pipeline];
                [enc setBuffer:g_dec_x offset:0 atIndex:0];
                [enc setBuffer:bufFfnOut offset:0 atIndex:1];
                [enc setBytes:&dim length:sizeof(int) atIndex:2];
                [enc dispatchThreads:MTLSizeMake(dim, 1, 1)
                    threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
                [enc endEncoding];
            }
        } /* end 26-layer loop */

        /* === Final RMSNorm === */
        id<MTLBuffer> bufFinalNorm = get_f32_buffer(dec->norm, dim);
        id<MTLBuffer> bufHidden = pool_get_buffer(dim * sizeof(float));
        {
            id<MTLComputeCommandEncoder> enc = [cmdBuffer computeCommandEncoder];
            [enc setComputePipelineState:g_rms_norm_pipeline];
            [enc setBuffer:g_dec_x offset:0 atIndex:0];
            [enc setBuffer:bufFinalNorm offset:0 atIndex:1];
            [enc setBuffer:bufHidden offset:0 atIndex:2];
            [enc setBytes:&dim length:sizeof(int) atIndex:3];
            float eps = TTS_DEC_NORM_EPS;
            [enc setBytes:&eps length:sizeof(float) atIndex:4];
            [enc dispatchThreadgroups:MTLSizeMake(1, 1, 1)
                threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
            [enc endEncoding];
        }

        /* === Submit single command buffer & wait === */
        [cmdBuffer commit];
        [cmdBuffer waitUntilCompleted];

        /* Download hidden state */
        memcpy(out_hidden, [bufHidden contents], dim * sizeof(float));

        /* Release pool buffers */
        pool_release_buffer(bufXnorm);
        pool_release_buffer(bufQKV);
        pool_release_buffer(bufAttn);
        pool_release_buffer(bufProj);
        pool_release_buffer(bufGate);
        pool_release_buffer(bufUp);
        pool_release_buffer(bufFfnOut);
        pool_release_buffer(bufHidden);
    } /* @autoreleasepool */
}

/* ========================================================================
 * LLM Prefill (all 26 layers, multi-token)
 *
 * TODO: Implement GPU prefill with batched MPS matmul.
 * For now, CPU prefill + shared memory KV cache is used.
 * ======================================================================== */

void tts_metal_llm_prefill(void *ctx, const float *embeds,
                            int seq_len, int start_pos) {
    /* CPU prefill is fast enough for ~225 tokens.
     * KV cache is in shared memory so GPU can read it directly. */
    (void)ctx; (void)embeds; (void)seq_len; (void)start_pos;
    fprintf(stderr, "  metal: prefill uses CPU (shared KV cache)\n");
}

/* ========================================================================
 * Acoustic Transformer Velocity Prediction
 *
 * TODO: Implement GPU acoustic transformer.
 * Currently falls back to CPU (3 tokens x 3 layers is small).
 * ======================================================================== */

void tts_metal_predict_velocity(void *ctx, float *out_velocity,
                                 const float *x_t, const float *llm_hidden,
                                 float t_val) {
    (void)ctx; (void)out_velocity; (void)x_t; (void)llm_hidden; (void)t_val;
}

/* ========================================================================
 * Utility
 * ======================================================================== */

void tts_metal_warmup_bf16(const uint16_t *bf16_weights, size_t num_elements) {
    if (!g_initialized) return;
    get_cached_f16_buffer(bf16_weights, num_elements);
}

size_t tts_metal_memory_used(void) {
    if (!g_device) return 0;
    return [g_device currentAllocatedSize];
}

#endif /* USE_METAL */
